# Generated by Django 4.1.8 on 2023-04-10 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=255)),
                ("is_pending", models.BooleanField(default=False)),
                ("date", models.DateField()),
                (
                    "total_rating",
                    models.IntegerField(
                        choices=[
                            (0, "Ingen brudd på regelverket funnet. Stort smil."),
                            (
                                1,
                                "Mindre brudd på regelverket som ikke krever oppfølging. Stort smil.",
                            ),
                            (
                                2,
                                "Brudd på regelverket som krever oppfølging. Strekmunn.",
                            ),
                            (3, "Alvorlig brudd på regelverket. Sur munn."),
                        ]
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InspectionTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.IntegerField(
                        choices=[
                            (1, "Rutiner og ledelse"),
                            (2, "Lokaler og utstyr"),
                            (3, "Mat-håndtering og tilberedning"),
                            (4, "Merking og sporbarhet"),
                        ]
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (0, "Ingen brudd på regelverket funnet. Stort smil."),
                            (
                                1,
                                "Mindre brudd på regelverket som ikke krever oppfølging. Stort smil.",
                            ),
                            (
                                2,
                                "Brudd på regelverket som krever oppfølging. Strekmunn.",
                            ),
                            (3, "Alvorlig brudd på regelverket. Sur munn."),
                        ]
                    ),
                ),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspection_themes",
                        to="inspections.inspection",
                    ),
                ),
            ],
        ),
    ]
