# Generated by Django 4.1.8 on 2023-04-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_number", models.CharField(max_length=9)),
                ("name", models.CharField(max_length=255)),
                ("postal_code", models.CharField(max_length=4)),
                ("postal_address", models.CharField(max_length=255)),
                ("address", models.TextField()),
            ],
        ),
    ]
